### ISSUE TITLE
Checking the cases in s_stSearches on jsonio branch ....

### ISSUE THREAD

**Issue by wandell** [vistalab/scitran#22]
I put both jsonio and jsonlab on my path, and I edited scitranClient to use jsonlab for writing the queries and jsonio for reading.  Speeds things up, and the _id problem is handled by jsonlab.  Ugly, but there it is.

Most things work.  These two searches don't.  Both appear connected to collections search.

I suspect that there may be problems with other _id cases in some of the upload code, but I am not sure.  We need some tests.

Thanks,
B

----
st = scitran('action', 'create', 'instance', 'scitran');

% Not working (the return is too large).  It should be 22 and it is 4400. 
clear srch; 
srch.path = 'sessions';
srch.collections.match.label = 'Anatomy Male 45-55';
sessions = st.search(srch);
fprintf('Found %d sessions\n',length(sessions));

% This is broken, too.  Maybe it has to do with collections?
clear srch
srch.path = 'files'; 
srch.collections.match.label = 'Anatomy Male 45-55';   
files = st.search(srch);

**Comment by rentzso** [comment]
This should have been fixed with https://github.com/scitran/core/commit/806e2d9f6770de1c4f244119fed032d7dcf56419

We probably need to upgrade the scitran instance. I'll check with @lmperry when we can do it.

**Comment by lmperry** [comment]
To get this fixed before the next release we can create a branch with this fix (based on the release) and install that branch.

**Comment by lmperry** [comment]
The patch was made this morning. 

```matlab
>> addpath(genpath('/Users/lmperry/Code/git/scitran/client'))
>> st = scitran('action', 'create', 'instance', 'scitran');
>> clear srch;
>> srch.path = 'sessions';
>> srch.collections.match.label = 'Anatomy Male 45-55';
>> sessions = st.search(srch);
>> fprintf('Found %d sessions\n',length(sessions));
Found 23 sessions
```
However, to my eye that should return 25 sessions, not 23. @rentzso subject code 101_J*
096_R* are in the collection and missing from the returned results. Those are both in the same project. My guess is that elastic is not indexing them properly. Perhaps because those subjects have `.info` fields that are causing elastic to skip indexing aspects of those docs?
![screen shot 2017-02-16 at 8 42 33 am](https://cloud.githubusercontent.com/assets/2119651/23030915/0ac837f4-f424-11e6-9764-1c81013394dc.png)

**Comment by lmperry** [comment]
Still investigating: Importantly, those two subjects also do not show up when searching for sessions with that project label. It does indeed appear to be related to (at least) those two subjects specifically.

**Comment by wandell** [comment]
The search has been substantially re-written, and we now use the master JSONio repository.  This issue no longer seems relevant.
