### ISSUE TITLE
configure_curl ...

### ISSUE THREAD

**Issue by wandell** [vistalab/scitran#3]
Perhaps we should edit the library path without eliminating directories on the current path.
Related, maybe we should store the current settings so we can return them when we are done.  
Brian/Michael to discuss.

**Comment by lmperry** [comment]
That's exactly what unconfigure_curl is meant to do. configure_curl returns the state of the env before it's changed, unconfigure_curl resets the env to what it was before it was configured (poor choice in naming - these were sub functions that we ripped out of other code). I can work on putting this functionality into a new function.
