### ISSUE TITLE
Search return seems wrong to me.

### ISSUE THREAD

**Issue by wandell** [vistalab/scitran#32]
On flywheel.scitran.stanford.edu, I am working with the ALDIT: Stanford CNI project.  I would like to find the bvecFile in a particular acquisition.  This search is not running correctly, I think.  

```
st = scitran('action', 'create', 'instance', 'scitran');

project = 'ALDIT: Stanford CNI';
subjectCode = '11671';
sessions = st.search('sessions',...
    'project label contains',project,...
    'file type','nifti',...
    'session contains subject',subjectCode, ...
    'summary',true);

%%  List the acquisitions in the first session
acquisitions = st.search('acquisitions', ...
    'session label',sessions{1}.source.label,...
    'summary',true);

%% Find the bvec from the first acquisition
bvecFile = st.search('files',...
    'acquisition label exact',acquisitions{1}.source.label,...
    'file type','bvec');
```

The last search returns three files, not one.  Here is a picture of the session{1} data.  As you will see, there is only 1 bvec file in each acquisition. BUT, two of the acquisitions have the same label, and some of the bvec files have the same name.  I think @lmperry put these data in by hand.

![screen shot 2017-05-27 at 6 20 53 pm](https://cloud.githubusercontent.com/assets/1837145/26525343/8a56f346-4309-11e7-8aa1-ec23968cd203.png)

Suggestions to avoid this problem - and I am not sure which is the real problem - are welcome.

**Comment by rentzso** [comment]
There are two acquisitions with the same label (13_1_DTI_pe0_b1k_mux3_24mm) and one of them has two bvec files. This seems to be weird...
Search for a specific acquisition should use the id as there could be multiple acquisitions across the DB with the same exact label.

**Comment by wandell** [comment]
In this case, it seems Michael should have organized the files and acquisition names differently.  Maybe we don't consider this a software issue, but just an upload issue?

I also agree that it is better to search with the _id field when possible.  Sometimes, though, the label is all you have.
