### ISSUE TITLE
Still getting the search is currently down error message

### ISSUE THREAD

**Issue by wandell** [vistalab/scitran#44]
Search errors return this message even though search is not down

```
>> file = fw.search('files','project label contains','SOC','filename','toolboxes.json');
Error using Flywheel.handleJson (line 999)
(503) Search is currently down. Try again later.
```

**Comment by jenreiter** [comment]
Hi @wandell, it looks like the search structure that you are using is in the format for your scitran search. Currently, the Flywheel search method requires a MATLAB struct, something similar to below...  

```
searchStruct = struct('return_type', 'session', ...
        'filters', {{struct('range', ...
        struct('subject_0x2E_age_in_years', ...
        struct('gte', 30, 'lt', 50) ...
        ))}});
sessions = fw.search(searchStruct)
```
This is my understanding unless something has changed. Nathaniel says nothing has changed with search to his knowledge. @lmperry any other thoughts? 

Thanks!

**Comment by wandell** [comment]
Hi @jenreiter 
The command in the query is a Matlab method that generates the search struct.  See scitran.search.

The search struct it creates and that fails, has this form
```
{"return_type":"file",
"filters":[
              {"match":{"session._id":"58f177c11f4a0300130d5fe1"}},
              {"term":{"file.type":"nifti"}}
             ],
"limit":-1}
```

**Comment by lmperry** [comment]
Turns out this is a bug with the `limit` in core. Now being tracked here: https://github.com/scitran/core/issues/1003.

Temporary work around is to limit to value <=10,000

**Comment by wandell** [comment]
Closing.
