### ISSUE TITLE
File info slot

### ISSUE THREAD

**Issue by wandell** [vistalab/scitran#45]
We see the file info data when we call acq = fw.getAcquisition.  The info is attached to each of the returned files, as in

```
acq = fw.getAcquisition(files{2}.parent.x_id)
acq.files{10}.info
```

What method can I use to get the file info when I know specific file.  (Not download the file, just get the info on the file).

**Comment by jenreiter** [comment]
There currently isn't a method to get the file info. We have methods to set, replace and delete acquisition file info (setAcquisitionFileInfo, replaceAcquisitionFileInfo, and deleteAcquisitionFileInfoFields) so I believe this could be easily added. 

@kofalt any comments on the feasibility of a method to get the file info?

**Comment by kofalt** [comment]
I'm not sure exactly what this ticket references - do you mean "given a file ID, access the file's info / other fields?" If so, that is largely blocked on scitran/core#937, so instead I would access the file's container.

**Comment by lmperry** [comment]
I don't think there's anything actionable here yet... We have been thinking about this a bit and what we're considering/proposing is a "higher-level" function that would return a file object when you specify the container._id and the file name.

Something like:

```python
fw.get_project_file(project_id, 'some_file_name')
fw.get_session_file(session_id, 'some_file_name')
fw.get_acquisition_file(acquisition_id, 'some_file_name')
fw.get_analysis_file(analysis_id, 'some_file_name')
```

The use case here is we want to be able to write analyses functions that operate on data within the info field of a given file when we know the file name and parent id, usually from the result of a search.

**Comment by kofalt** [comment]
Yeah - it would be even better if we can get rid of container nouns, so 5x fewer functions.
Something like this:

```python
fw.get_container_file(123, 'file.txt')
# use any container ID, don't need to say project / etc

fw.get_file(345, 'file.txt')
# fetch based with only a file ID, once files become 1st-class
```

The aforementioned scitran/core#937 will help a lot with the first one.

**Comment by wandell** [comment]
We now have an example usage case, getdicominfo.  We will write a getQAinfo case next week.  Perhaps these examples will help us understand what to do in the SDK.
