### ISSUE TITLE
Add login capability

### ISSUE THREAD

**Issue by wandell** [vistalab/scitran#8]
@gsfr has the ability for us to login from the command line using oAuth.  We should incorporate this.

**Comment by gsfr** [comment]
@wandell Are you referring to the API key functionality in core?

**Comment by wandell** [comment]
Probably.

**Comment by gsfr** [comment]
The API functionality is ready to go.

@dpuccetti What's the ETA on getting the user's API key exposed in the UI?

**Comment by dpuccetti** [comment]
@gsfr There is currently a front end pull request with the styles: https://github.com/flywheel-io/frontend/pull/535.  I just need to add the API functionality, which is scheduled for this week.  I'll reach out to Megan to get some docs or usage examples tomorrow.

**Comment by wandell** [comment]
How about if I just want to use it from the command line interface?

**Comment by gsfr** [comment]
@wandell An API key is a non-expiring authentication token for a particular user. The idea is to create and retrieve an API key via the UI (by going through the normal login process) and subsequently use it for authentication in other applications, such as client or organizer.

@wandell @dpuccetti API key creation and usage is documented in https://github.com/scitran/core/pull/386.
